### ISSUE TITLE
Another exception was thrown: Unsupported operation: NetworkInterface.list

### ISSUE THREAD

**Issue by PsEHAmfxXNKzrgwT** [iamEtornam/EtornamVpnFlutter#1]
**Describe the bug**

**To Reproduce**
1. Clone repo
2. `C:\path\to\project> flutter pub get`
3. `C:\path\to\project> flutter run`

**Expected behavior**
App runs

**Screenshots**
<img width="1388" alt="NVIDIA_Share_wEQu5ZKmyg" src="https://user-images.githubusercontent.com/2437782/229743441-8bf46346-0f33-48ea-951f-731e1eccfeb5.png">

**Desktop**
 - OS: Windows 11
 - Browser Chrome

**Additional context**
Hi,

I have just recently cloned your repo and tried running it. I am getting this error. Could you assist? It would be greatly appreciated :)

Thank you!

**Comment by PsEHAmfxXNKzrgwT** [comment]
When I comment out that line in home_page.dart the app runs. 

![image](https://user-images.githubusercontent.com/2437782/229749099-9201bc08-38af-4ab1-8358-ea59da3408cc.png)

**Comment by iamEtornam** [comment]
unfortunately, the [VPN package](https://pub.dev/packages/flutter_vpn) I am using doesn't support the web. Just Android & iOS
